urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from core.views import *  # flat import
from core.views_other import *
from core.views_caves import *
from core.views_survex import *
from core.models import *
from django.views.generic.create_update import create_object
from django.views.generic.list_detail import object_list, object_detail
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.contrib import databrowse
import datalogging.models
import datalogging.views
admin.autodiscover()


# type url probably means it's used.

urlpatterns = patterns('',

    url(r'^timeseries_stats/(?P<data_type>.*)$',     datalogging.views.monthly_stats,      name="caves"),    
    
    url(r'^$',              views_other.frontpage,      name="frontpage"),
    url(r'^testing/$',              views_other.frontpagetesting,      name="frontpagetesting"),
    url(r'^alarms/$',              views_other.alarms,      name="alarms"),
    url(r'^todo/$',              views_other.todo,      name="todo"),
    url(r'^about/$',             direct_to_template, {'template': 'about.html'}, name="about"),
    (r'^ajax/$',             views_other.cave_stats_ajax),
    (r'^coords_ajax/$',             views_other.entrance_location_ajax),
    (r'^timeseries/$',             datalogging.views.ajax_timeseries_data),
    (r'^timeseries_chart/?$',             datalogging.views.availability),
    (r'^comments/', include('django.contrib.comments.urls')),

    url(r'^caves/$',     views_caves.caveindex,      name="caves"),
    url(r'^people/?$',   views_logbooks.personindex, name="personindex"),
    url(r'^plots/?$',   object_list, {'queryset':Timeseries.objects.all(),'template_name':'timeseries_list.html'}, name="plots"),

    url(r'^newqmnumber/?$',              views_other.ajax_QM_number,  ),
    url(r'^lbo_suggestions/?$',              logbook_entry_suggestions),    
    #(r'^person/(?P<person_id>\d*)/?$', views_logbooks.person),
    url(r'^person/(?P<first_name>[A-Z]*[a-z\-\']*)[^a-zA-Z]*(?P<last_name>[a-z\-\']*[^a-zA-Z]*[A-Z]*[a-z\-]*)/?', views_logbooks.person, name="person"),
    #url(r'^person/(\w+_\w+)$',       views_logbooks.person,      name="person"),
    
    url(r'^expedition/(\d+)$',  views_logbooks.expedition,  name="expedition"),
    url(r'^expeditions/?$',  object_list,  {'queryset':Expedition.objects.all(),'template_name':'object_list.html'},name="expeditions"),
    url(r'^personexpedition/(?P<first_name>[A-Z]*[a-z]*)[^a-zA-Z]*(?P<last_name>[A-Z]*[a-z]*)/(?P<year>\d+)/?$', views_logbooks.personexpedition, name="personexpedition"),
    url(r'^logbookentry/(?P<date>.*)/(?P<slug>.*)/?$', views_logbooks.logbookentry,name="logbookentry"),

    url(r'^cave/(?P<cave_id>[^/]+)/?$', views_caves.cave, name="cave"),
    url(r'^cavedescription/(?P<cavedescription_name>[^/]+)/?$', views_caves.cave_description, name="cavedescription"),
    url(r'^cavedescription/?$', object_list, {'queryset':CaveDescription.objects.all(),'template_name':'object_list.html'}, name="cavedescriptions"),
    #url(r'^cavehref/(.+)$',     views_caves.cave,       name="cave"),url(r'cave'),

    url(r'^jgtfile/(.*)$',      view_surveys.jgtfile,       name="jgtfile"),
    url(r'^jgtuploadfile$',     view_surveys.jgtuploadfile, name="jgtuploadfile"),

    
    url(r'^photo_gallery/?$',      object_list,  {'queryset':Photo.objects.all(), 'template_name':'photo_list.html'}, name="photos" ),
    
    url(r'^cave/(?P<cave_id>[^/]+)/?(?P<ent_letter>[^/])$', ent),
    #(r'^cave/(?P<cave_id>[^/]+)/edit/$', edit_cave),
    #(r'^cavesearch', caveSearch),

    
    url(r'^cave/(?P<cave_id>[^/]+)/(?P<year>\d\d\d\d)-(?P<qm_id>\d*)(?P<grade>[ABCDX]?)?$', views_caves.qm, name="qm"),
    
    
    url(r'^logbooksearch/(.*)/?$', views_logbooks.logbookSearch),

        
    url(r'^statistics/?$', views_other.stats, name="stats"),
    
    url(r'^survey/?$', surveyindex, name="survey"),
    url(r'^survey/(?P<year>\d\d\d\d)\#(?P<wallet_number>\d*)$', survey, name="survey"),

    url(r'^controlpanel/?$', views_other.controlPanel, name="controlpanel"),
    url(r'^CAVETAB2\.CSV/?$', views_other.downloadCavetab, name="downloadcavetab"),
    url(r'^caves\.csv/?$', views_other.downloadHubetab, name="downloadhubetab", ),
    url(r'^Surveys\.csv/?$', views_other.downloadSurveys, name="downloadsurveys"),
    url(r'^logbook(?P<year>\d\d\d\d)\.(?P<extension>.*)/?$',views_other.downloadLogbook),
    url(r'^logbook/?$',views_other.downloadLogbook, name="downloadlogbook"),
    url(r'^cave/(?P<cave_id>[^/]+)/qm\.csv/?$', views_other.downloadQMs, name="downloadqms"),        
    (r'^downloadqms$', views_other.downloadQMs),
   
    url(r'^eyecandy$', views_other.eyecandy),

    (r'^admin/doc/?', include('django.contrib.admindocs.urls')),
    ('^admin/', include(admin.site.urls)),
    
    (r'^databrowse/(.*)', databrowse.site.root),

    
    # don't know why this needs troggle/ in here.  nice to get it out
    url(r'^troggle/media-admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ADMIN_DIR, 'show_indexes':True}),


    (r'^accounts/', include('registration.urls')),
    (r'^profiles/', include('profiles.urls')),

        
#   (r'^personform/(.*)$', personForm),

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                
        
    url(r'^survexblock/(.+)$',                     views_caves.survexblock, name="survexblock"),
    url(r'^survexfile/(?P<survex_file>.*?)\.svx$', views_survex.svx,        name="svx"),
    url(r'^survexfile/(?P<survex_file>.*?)\.3d$',  views_survex.threed,     name="threed"),
    url(r'^survexfile/(?P<survex_file>.*?)\.log$', views_survex.svxraw),
    url(r'^survexfile/(?P<survex_file>.*?)\.err$', views_survex.err),
    
            
    url(r'^survexfile/caves/$',                     views_survex.survexcaveslist,  name="survexcaveslist"),
    url(r'^survexfile/caves/(?P<survex_cave>.*)$',  views_survex.survexcavesingle, name="survexcavessingle"),
    url(r'^survexfileraw/(?P<survex_file>.*?)\.svx$', views_survex.svxraw,         name="svxraw"),
            
                
    (r'^survey_files/listdir/(?P<path>.*)$',       view_surveys.listdir),
    (r'^survey_files/download/(?P<path>.*)$',      view_surveys.download),
    #(r'^survey_files/upload/(?P<path>.*)$', view_surveys.upload),

    
            
    (r'^survey_scans/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.SURVEY_SCANS, 'show_indexes':True}),
    #url(r'^survey_scans/$',                        view_surveys.surveyscansfolders, name="surveyscansfolders"), 
    #url(r'^survey_scans/(?P<path>[^/]+)/$',        view_surveys.surveyscansfolder,  name="surveyscansfolder"), 
    #url(r'^survey_scans/(?P<path>[^/]+)/(?P<file>[^/]+(?:png|jpg))$', view_surveys.surveyscansingle,   name="surveyscansingle"), 
    
    url(r'^tunneldata/$',                          view_surveys.tunneldata,         name="tunneldata"), 
    url(r'^tunneldataraw/(?P<path>.+?\.xml)$',     view_surveys.tunnelfile,         name="tunnelfile"), 
    url(r'^tunneldataraw/(?P<path>.+?\.xml)/upload$',view_surveys.tunnelfileupload, name="tunnelfileupload"), 
    url(r'^tunneldataraw/(?P<path>.+?\.xml)/backgroundscan/(?P<backgroundscan>.*)$', 
                                                   view_surveys.tunnelfilebackgroundscan), 
            
    #url(r'^tunneldatainfo/(?P<path>.+?\.xml)$',    view_surveys.tunnelfileinfo,     name="tunnelfileinfo"), 

    # for those silly ideas
    url(r'^experimental.*$',                         views_logbooks.experimental,  name="experimental"),
    
    (r'^photos/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.PHOTOS_ROOT}),

)

from datalogging.models import *

databrowse.site.register(Manufacturer)
databrowse.site.register(EquipmentType)
databrowse.site.register(EquipmentItem)
databrowse.site.register(Timeseries)
databrowse.site.register(DataPoint)

datalogging/forms.py
from django import forms
from datalogging.models import Timeseries
from django.contrib.auth.models import User

class TimeseriesDataForm(forms.Form):
    timeseries=forms.ModelChoiceField(queryset=Timeseries.objects.all())
    start_time=forms.DateTimeField(required=False,)
    end_time=forms.DateTimeField(required=False,)
    number_of_samples=forms.IntegerField(
        required=False,
        help_text="<span class='helptext'>Leave blank to load all samples. Entering a smaller number of than the database contains will resample the data using fast Fourier methods.</span>")
    FORMAT_CHOICES=(('JSON','Add to chart'),('csv','Download .csv table'),('matlab','Download Matlab .mat data file'),('newpage','Autoload'),('stats','Load statistics'))
    action=forms.ChoiceField(choices=FORMAT_CHOICES)

class UnauthTimeseriesDataForm(forms.Form):
    timeseries=forms.ModelChoiceField(queryset=Timeseries.objects.all())
    start_time=forms.DateTimeField(required=False,)
    end_time=forms.DateTimeField(required=False,)
    number_of_samples=forms.IntegerField(
        required=False,
        help_text="<span class='helptext'>Leave blank to load all samples. Entering a smaller number of than the database contains will resample the data using fast Fourier methods.</span>")
    FORMAT_CHOICES=(('JSON','Add to chart'),('newpage','Autoload'),('stats','Load statistics'),('na','[login required for data download]'))
    action=forms.ChoiceField(choices=FORMAT_CHOICES)

datalogging/views.py
from utils import render_with_context
from django.conf import settings
from django.shortcuts import render_to_response
from datalogging.models import Timeseries, DataPoint
from datalogging import to_matlab, export_csv, processing
from datalogging.forms import TimeseriesDataForm, UnauthTimeseriesDataForm
from django.http import HttpResponse
from django.utils import simplejson
from django.db.models import Q, Count, Max, Min
import numpy as np
import os, datetime
from time import strptime

def ajax_timeseries_data(request):
    num_samples=request.GET.get('num_samples')
    #convert to an integer if it exists
    if num_samples:
        num_samples=int(num_samples)

    start_time=request.GET.get('start_time')
    end_time=request.GET.get('end_time')
    if not request.user.is_authenticated():
        form=UnauthTimeseriesDataForm
    else:
        form=TimeseriesDataForm
    
    if request.GET:
        form=form(request.GET)
        if form.is_valid():
            num_samples=form.cleaned_data['number_of_samples']
            start_time=form.cleaned_data['start_time']
            end_time=form.cleaned_data['end_time']
            number_of_samples=form.cleaned_data['number_of_samples']
            ts=form.cleaned_data['timeseries']
            if form.cleaned_data['action']=='JSON':
                #ts=Timeseries.objects.get(pk=ts_pk)
                data=ts.data_cropped_resampled(num_samples=num_samples, time_range_crop=(start_time, end_time), style='flot')
                return HttpResponse(simplejson.dumps(data), mimetype="application/javascript")
            elif form.cleaned_data['action']=='stats':
                #ts=Timeseries.objects.get(pk=ts_pk)
                start_time, end_time=ts.auto_date_range()
                num_samples=ts.datapoint_set.count()
                return HttpResponse(simplejson.dumps({'ts':ts.pk,'start_time':str(start_time), 'end_time':str(end_time), 'number_of_samples':num_samples}), mimetype="application/javascript")
            elif form.cleaned_data['action']=='csv':
                response=HttpResponse()
                export_csv.export_to_csv(response, (start_time, end_time), (ts,), samples_per_ts=number_of_samples) #it expects a set of timeseries, not just one so we trick it
                response['Content-Disposition']='attachment; filename=%s%s.csv' % ('erebus_caves_ts_',ts.pk)
                return response

            elif form.cleaned_data['action']=='matlab':
                # note: does not chop dates yet
                response=HttpResponse()
                response['Content-Disposition']='attachment; filename=%s%s.mat' % ('erebus_caves_ts_',ts.pk)
                date_format='%Y-%m-%d %H:%M:%S'
                to_matlab.make_mat(response,date_range=(start_time, end_time),ts_pk_list=[ts.pk],samples_per_ts=number_of_samples)
                return response
            elif form.cleaned_data['action']=='newpage':
                return render_with_context(request,'timeseries_browser.html',{'ts_form':form,'auto_click_submit':True})

  
        elif form.is_bound:
            return render_with_context(request,'timeseries_browser.html',{'ts_form':form,})
    else:
        form = form()
        return render_with_context(request,'timeseries_browser.html',{'ts_form':form,})
        
def monthly_stats(request, data_type):
    tses=Timeseries.objects.filter(data_type=data_type)
    template_file='timeseries_stats.html'
    #set the defaults
    overall_stats=None
    plot=False
    if request.GET:
        pk_list=request.GET.getlist('ts')
        print pk_list
        tses=tses.filter(logbook_entry__cave__slug__in=pk_list)
        print tses
        if 'overall' in request.GET:
            overall_stats=processing.monthly_stats_multiple(pk_list, data_type=data_type)
        if 'plot' in request.GET:
            plot=True
            
    return render_with_context(request,template_file,{'timeseries': tses,'overall_stats':overall_stats,'plot':plot})

def add_one_month(dt0):
    """
    Unfortunately required to add a month to a datetime.
    """
    dt1 = dt0.replace(day=1)
    dt2 = dt1 + datetime.timedelta(days=32)
    dt3 = dt2.replace(day=1)
    return dt3

def monthly_counts():
    entireTimestampRange=DataPoint.objects.aggregate(Min('time'),Max('time'))
    months=[]
    monthly_counts=[]
    currentMonth=entireTimestampRange['time__min']
    x=0
    while currentMonth < entireTimestampRange['time__max']:
        currentMonth=add_one_month(currentMonth)
        x+=1
        res=DataPoint.objects.filter(time__month=currentMonth.month,time__year=currentMonth.year).order_by('parent_timeseries').annotate(dpcount=Count('parent_timeseries'))
        res.query.group_by=['parent_timeseries_id']
        monthly_counts.append(dict(zip(res.values_list('parent_timeseries_id',flat=True),res.values_list('dpcount',flat=True))))
        months.append(currentMonth)
    return {'months':months, 'counts':monthly_counts, 'timeserieses':Timeseries.objects.all().values_list('pk',flat=True),'tstest':[1,2,3,4,5]}

def availability(request):
    return render_with_context(request,'timeseries_availability.html',monthly_counts())

datalogging/templates/timeseries_availability.html
{% extends "base.html" %}
{% block content %}
<table>
     <th>Timeseries pk</th>
{% for tspk in tstest %}    
    <tr>
        <td>
            {{tspk}}
        </td>
        {% for monthcount in counts %}
            <td>{{monthcount.tspk}}</td>
        {% endfor %}
    </tr>

{% endfor %}
</table>

{% endblock %}

datalogging/templates/timeseries_browser.html
{% extends "base.html" %}

{% block head %}
<script src="{{ settings.MEDIA_URL }}js/anytime.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{{ settings.MEDIA_URL }}css/anytime.css"/>
<script>
$(document).ready(function () {
    var plottedData = [];
    var overviewOptions = {
        xaxis: {mode:'time',tickLength: 0},
        yaxis: {tickLength: 0},
        legend: {show:false},
        selection: { mode: "xy" },
	grid: {backgroundColor: "#F9F9F9"}
        }
    //an ajax request to get start time, end time, and number of samples
    getTsStats = function (ts_pk) {
        $.ajax({
          url: '{{settings.URL_ROOT}}timeseries/',
          data: {'timeseries': ts_pk, 'action':'stats'},
          success: function (data){
                        $('#id_start_time').attr('value',data['start_time']);
                        $('#id_end_time').attr('value',data['end_time']);

                        $('#id_start_time').AnyTime_noPicker();
                        $('#id_end_time').AnyTime_noPicker();

                        $('#id_start_time').AnyTime_picker({earliest:data['start_time']});
                        $('#id_end_time').AnyTime_picker({latest:data['end_time']});

                        $('#id_number_of_samples').attr('value',data['number_of_samples']);
                   },
          dataType:'json',
          beforeSend: function () { $('#loading').fadeIn() },
          complete: function() { $('#loading').fadeOut() },
          })
    };

    //function for adding new data
    plotNewData = function(series) {
        plottedData.push(series);
        plot=$.plot($('#graph'), plottedData, options);
        //if overview is showing, then we re-plot it with the new data. If it's not showing then we can't because flot would have troubles.
        if ($('#overview').is(":visible")){
            overview=$.plot($('#overview'), plottedData, overviewOptions);};
        $(this).remove();
        refreshRemoverButtons(plottedData);
    };

    ajaxError = function() {
        alert('There was a problem with your request. Make sure you are not requesting a higher sample rate than the original sample rate.');
    };
    
    // sqare symbol lifted from jquery.flot.symbol.js plugin
	square = function (ctx, x, y, radius, shadow) {
                // pi * r^2 = (2s)^2  =>  s = r * sqrt(pi)/2
                var size = radius * Math.sqrt(Math.PI) / 2;
                ctx.rect(x - size, y - size, size + size, size + size);
            };


    //Due to my supreme laziness, this options object is for both the ajax form and the Flot graph! Maybe fix that...
    var options = {
        dataType: 'json',
        success: plotNewData,
        beforeSend: function () { $('#loading').fadeIn() },
        error: ajaxError,
        complete: function() { $('#loading').fadeOut() },
        xaxis: {mode:'time'},
        selection: { mode: "xy" },
        legend: {show:true},
	lines: {show:false},
	points: {show:true, symbol:square, radius:1}
        }

{% if auto_click_submit %}
    $("option[value='JSON']").attr('selected','selected');
    $('#ts_form').ajaxSubmit(options);
{% endif %}

    //function for updating the "remove data" buttons
    refreshRemoverButtons = function(plottedData){
        // show the header for the remover buttons
        $('#removerLabel').attr('visibility','show')

        // blank the list of remover buttons
        $('#alreadyFetched').replaceWith("<div class='center alreadyFetched' id='alreadyFetched'></div>");
        // for each shown plot
        $.each(plottedData,
            function(index, value){

                $('#alreadyFetched').append("<p><input type='submit' class='alreadyFetched' value='Remove "+ value['label'] +"' id='remove"+ value['label'] +"'></p>");
                $('input:last').click(function() {
                    plottedData.splice(index,1)
                    $.plot($('#graph'), plottedData, options);
                    //if overview is showing, then we re-plot it with the new data. If it's not showing then we can't because flot would have troubles.
                    if ($('#overview').is(":visible")){
                        overview=$.plot($('#overview'), plottedData, overviewOptions);};
                    $(this).remove();
                    refreshRemoverButtons(plottedData);
                });

             });        
    };

    //handling clicking on the button to get data, stats, etc
    $('#ts_form').submit(
        function() {
            if ($("option[value='matlab']").attr('selected') || $("option[value='csv']").attr('selected')){
                return true; 
                }
            else {
                $(this).ajaxSubmit(options);
                return false;
                }
        }
    );

    $('#id_start_time').AnyTime_picker();
    $('#id_end_time').AnyTime_picker();

    $('#id_timeseries').change(
        function(){
            getTsStats(this.value)
        })

//    var plot = $.plot($('#graph'),
//    plottedData,
//     {xaxis: {mode:"time"}, selection: { mode: "xy" }, points: { show: true}, lines: {show: true}, color: "Black", clickable: true, hoverable: true}
//     );

    // setup overview
    $("#graph").bind("plotselected", function (event, ranges) {
        // clamp the zooming to prevent eternal zoom
        if (ranges.xaxis.to - ranges.xaxis.from < 0.00001)
            ranges.xaxis.to = ranges.xaxis.from + 0.00001;
        if (ranges.yaxis.to - ranges.yaxis.from < 0.00001)
            ranges.yaxis.to = ranges.yaxis.from + 0.00001;
        
        // do the zooming
        $('#overview').show();
        plot = $.plot($("#graph"), plottedData,
                      $.extend(options,{xaxis: {mode:"time", min: ranges.xaxis.from, max: ranges.xaxis.to},
                          yaxis: { min: ranges.yaxis.from, max: ranges.yaxis.to}})
                      );
        overview=$.plot($('#overview'), plottedData, overviewOptions);
        
        // don't fire event on the overview to prevent eternal loop
        overview.setSelection(ranges, true);
    });

    $("#overview").bind("plotselected", function (event, ranges) {
        plot.setSelection(ranges);
    });

});

</script>

{% endblock head %}

{% block content%}
<h3>Timeseries browser</h3>
<div style="width:70%;height:400px;position:relative;margin-left:auto;margin-right:auto">
    <div id="graph" style="height:400px"></div>
    <div id="overview" style="height:150px; width:200px;position:absolute;bottom:40px;left:40px;display:none;"></div>
</div>
<h2>Get data</h2>
<form action="{{settings.URL_ROOT}}timeseries/" method="GET" id="ts_form">
<table class="center">
{{ts_form.as_table}}
<tr><td colspan=2><input type="submit" value="Do it!" /></td></tr>
</table>
</form>
<h2 id="removerLabel" style="display:none;">Remove data from the plot</h2>
<div class="center" id="alreadyFetched">
</div>
</form>

{% endblock content%}

datalogging/templates/timeseries_hist_plot.html
<script language='javascript' >
$(document).ready(function() {

var hist_datapoints=[{% for point in timeseries.histogram %}[{{point.0}},{{point.1}}],{% endfor %} ]

var plot = $.plot($('#{{timeseries.id}}_histgraph_id'),
[hist_datapoints],
 { title:'{{timeseries}}',}
 );


 
});
</script>

datalogging/templates/timeseries_list.html
{% extends "base.html" %}
{% load wiki_markup %}
{% load comments %}


{% block head %}
    {% for timeseries in object_list %}
        {{timeseries.plot}}
    {% endfor %}
{% endblock head %}


{% block content %}
    {% for timeseries in object_list %}
	Timeseries from {{ timeseries.logbook_entry.cave }} . Data type: {{ timeseries.data_type }}.
    <div id="both_graphs_{{timeseries.id}}"  class="timeseries_graph">
        
        <div id='{{timeseries.id}}_graph_id'  class="main_graph"></div>
        <div id='{{timeseries.id}}_overview_graph_id' class="overview_graph"></div>
        <p style="clear:left;">T{{timeseries.pk}}: {{timeseries}}</p>
        <p style="clear:left;">Y axis: {{timeseries.data_type}}</p>
        <p style="clear:left;">X axis: time</p>
        {{timeseries.comments}}
    </div>
    
    {% endfor %}
{% endblock content %}

datalogging/templates/timeseries_plot.html
<script language='javascript' >
$(document).ready(function() {

var datapoints=[{% for point in timeseries.datapoint_set.all %}[{{point.epoch_time|floatformat}},{{point.value}}],{% endfor %} ]

var plot = $.plot($('#{{timeseries.id}}_graph_id'),
[datapoints],
 { title:'{{timeseries}}',  xaxis: { mode:'time'}, selection: { mode: "xy" }, points: { show: true}, lines: {show: true}, color: "Black", clickable: true, hoverable: true}
 );

// setup overview
var overview = $.plot($("#{{timeseries.id}}_overview_graph_id"), [datapoints], {
    selection: { mode: "xy" },  xaxis: { mode:'time'}
});

    $("#{{timeseries.id}}_graph_id").bind("plotselected", function (event, ranges) {
        // clamp the zooming to prevent eternal zoom
        if (ranges.xaxis.to - ranges.xaxis.from < 0.00001)
            ranges.xaxis.to = ranges.xaxis.from + 0.00001;
        if (ranges.yaxis.to - ranges.yaxis.from < 0.00001)
            ranges.yaxis.to = ranges.yaxis.from + 0.00001;
        
        // do the zooming
        plot = $.plot($("#{{timeseries.id}}_graph_id"), [datapoints],
                      $.extend(true, {}, { title:'{{timeseries}}',  xaxis: { mode:'time'}, selection: { mode: "xy" }, points: { show: true}, lines: {show: true}, color: "Black", clickable: true, hoverable: true}, {
                          xaxis: { min: ranges.xaxis.from, max: ranges.xaxis.to },
                          yaxis: { min: ranges.yaxis.from, max: ranges.yaxis.to }
                      }));
        
        // don't fire event on the overview to prevent eternal loop
        overview.setSelection(ranges, true);
    });
    $("#{{timeseries.id}}_overview_graph_id").bind("plotselected", function (event, ranges) {
        plot.setSelection(ranges);
    });

 
});
</script>